import {Product} from './models/product';

export const cards: Product[] = [
    {
        name: 'RDR2',
        alt: 'Red Dead Redemption 2 cover',
        price: 150_000,
        percentOff: 30,
        imgSrc: 'assets/images/cards/rdr2.webp',
        points: 9.3,
    },
    {
        name: 'Dota 2',
        alt: 'Dota 2 cover',
        price: 200_000,
        percentOff: 50,
        imgSrc: 'assets/images/cards/dota2.webp',
        points: 9.5,
    },
    {
        name: 'God of War',
        alt: 'God of War cover',
        price: 1_500_000,
        percentOff: 20,
        imgSrc: 'assets/images/cards/god-of-war.webp',
        points: 10,
    },
    {
        name: 'RDR2',
        alt: 'عکسی RDR2',
        price: 150_000,
        percentOff: 30,
        imgSrc: 'assets/images/cards/rdr2.webp',
        points: 9.3,
    },
    {
        name: 'Horizon Zero Down',
        alt: 'Horizon Zero Down cover',
        price: 110_000,
        percentOff: 35,
        imgSrc: 'assets/images/cards/horizon.webp',
        points: 8,
    },
    {
        name: 'God of War',
        alt: 'God of War cover',
        price: 1_500_000,
        percentOff: 20,
        imgSrc: 'assets/images/cards/god-of-war.webp',
        points: 10,
    },
    {
        name: 'Dota 2',
        alt: 'Dota 2 cover',
        price: 200_000,
        percentOff: 50,
        imgSrc: 'assets/images/cards/dota2.webp',
        points: 9.5,
    },
    {
        name: 'Horizon Zero Down',
        alt: 'Horizon Zero Down cover',
        price: 110_000,
        percentOff: 35,
        imgSrc: 'assets/images/cards/horizon.webp',
        points: 8,
    },
];
